
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE ejercicio12 (i_Dep IN VARCHAR) IS

    vDepartamento DEPARTAMENTO.NOMBRE%TYPE:=i_Dep;
    vFecha DATOSPERSONALES.FECHA_ALTA%TYPE;
    vFechaActual DATE;

BEGIN

    --SACAMOS LA FECHA MAS ANTIGUA DEL DEPARTAMENTO RECIBIDO

    SELECT MIN(FECHA_ALTA) INTO vFecha FROM DATOSPERSONALES,DEPARTAMENTO,EMPLEADOS 
    WHERE  DEPARTAMENTO.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO
    AND EMPLEADOS.ID_EMPLEADO = DATOSPERSONALES.CLAVE_EMPLEADO
    AND DEPARTAMENTO.NOMBRE=vDepartamento;
    
    
    --SACAMOS LA FECHA DE HOY
    SELECT SYSDATE INTO vFechaActual FROM DUAL;
    
    
    UPDATE DATOSPERSONALES SET FECHA_ALTA=vFechaActual WHERE FECHA_ALTA=vFecha;
    DBMS_OUTPUT.PUT_LINE('OK');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No existe ese departamento');
END;

CALL ejercicio12('Personal');

SELECT FECHA_ALTA FROM DATOSPERSONALES ORDER BY FECHA_ALTA DESC;